---
- hosts: localhost
  connection: local
  roles:
    - gitignore
    - rbenv
  vars:
    gitignore_files:
      - Global/Ansible
      - Global/Dropbox
      - Global/Redis
      - Global/SublimeText
      - Global/Vagrant
      - Global/VirtualEnv
      - Global/XCode
      - Global/macOS
