---
- hosts: localhost
  connection: local
  roles:
    - { role: gitignore, tags: [ 'gitignore' ] }
    - rbenv
  tasks:
    - homebrew:
        name: '{{ item }}'
        state: present
        update_homebrew: yes
      with_items:
        - flow
        - watchman
      tags:
        - brew
        - homebrew

    - homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items:
        - caskroom/cask
      tags:
        - brew
        - homebrew

    - homebrew_cask:
        name: '{{ item }}'
        state: present
      with_items:
        - haskell-platform
      tags:
        - brew
        - homebrew

  vars:
    gitignore_files:
      - Global/Ansible
      - Global/Dropbox
      - Global/Redis
      - Global/SublimeText
      - Global/Vagrant
#      - Global/VirtualEnv
      - Global/XCode
      - Global/macOS
      - Node
