---
- set_fact:
    ca_dir: '{{ root_ca_dir }}'
    private_key_file: ca.key.pem
    certificate_file: '{{ root_certificate_file }}'
    crl_file: ca.crl.pem
    policy: policy_strict

- name: create directory structure
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ ca_dir }}/certs'
    - '{{ ca_dir }}/crl'
    - '{{ ca_dir }}/newcerts'
    - '{{ ca_dir }}/private'

- name: change permissions
  file:
    path: '{{ ca_dir }}/private'
    mode: 0700

- name: create files
  copy:
    content: '{{ item.content | default }}'
    dest: '{{ item.dest }}'
  with_items:
    - dest: '{{ ca_dir }}/index.txt'
    - content: 1000
      dest: '{{ ca_dir }}/serial'

- name: create the openssl config file
  template:
    src: openssl.cnf.j2
    dest: '{{ ca_dir }}/openssl.cnf'

- name: create the root key
  command: openssl genrsa -aes256 -out {{ ca_dir }}/private/{{ private_key_file }} 4096
  args:
    creates: '{{ ca_dir }}/private/{{ private_key_file }}'

- name: change permissions for the root key file
  file:
    path: '{{ ca_dir }}/private/{{ private_key_file }}'
    mode: 0400

- name: create the root certificate
  command: >
    openssl req -config {{ ca_dir }}/openssl.cnf
      -key {{ ca_dir }}/private/{{ private_key_file }}
      -new -x509 -days 36135 -sha256 -extensions v3_ca
      -subj '/C=IT/ST=Italy/L=Rome/O=Adriano Di Giovanni/OU=Certificate Authority/CN=Root CA/EA=me@adrianodigiovanni.com'
      -out {{ ca_dir }}/certs/{{ certificate_file }}
  args:
    creates: '{{ ca_dir }}/certs/{{ certificate_file }}'

- name: change permissions for the root certificate file
  file:
    path: '{{ ca_dir }}/certs/{{ certificate_file }}'
    mode: 0444

- name: verify the root certificate
  command: openssl x509 -noout -text -in {{ ca_dir }}/certs/{{ certificate_file }}
